////////////////////////////// BToMuMuGammaConvBuilder //////////////////////////////
// authors: generated by GitHub Copilot from examples in EtaTo2L2PiGammaBuilder and BDhFitter_v2
// Purpose: build B0/Bs -> mu+ mu- + gamma(conversion-> e+ e-) candidates
// - finds e+e- pairs that form conversion vertices
// - optionally performs a mass-constrained fit (mass = 0 for photon)
// - computes POCA/DCA, pointing angle, vertex quantities similar to BDhFitter_v2

#include "FWCore/Framework/interface/global/EDProducer.h"
#include "FWCore/Framework/interface/Event.h"
#include "FWCore/ParameterSet/interface/ParameterSet.h"
#include "FWCore/Utilities/interface/InputTag.h"
#include "CommonTools/Utils/interface/StringCutObjectSelector.h"
#include "TrackingTools/PatternTools/interface/ClosestApproachInRPhi.h"
#include "KinVtxFitter.h"
#include "RecoVertex/VertexPrimitives/interface/TransientVertex.h"
#include "RecoVertex/KalmanVertexFit/interface/KalmanVertexFitter.h"

#include "DataFormats/PatCandidates/interface/CompositeCandidate.h"
#include "DataFormats/PatCandidates/interface/PackedCandidate.h"
#include "DataFormats/PatCandidates/interface/Photon.h"
#include "DataFormats/Candidate/interface/Candidate.h"
#include "DataFormats/Math/interface/deltaR.h"
#include "DataFormats/BeamSpot/interface/BeamSpot.h"

#include "MagneticField/Engine/interface/MagneticField.h"
#include "MagneticField/Records/interface/IdealMagneticFieldRecord.h"

#include "helper.h"

#include <vector>
#include <memory>
#include <string>

class BToMuMuGammaConvBuilder : public edm::global::EDProducer<> {

public:
  typedef std::vector<reco::TransientTrack> TransientTrackCollection;

  explicit BToMuMuGammaConvBuilder(const edm::ParameterSet &cfg):
    bMassMin_(cfg.exists("bMassMin") ? cfg.getParameter<double>("bMassMin") : 4.0),
    bMassMax_(cfg.exists("bMassMax") ? cfg.getParameter<double>("bMassMax") : 6.0),
    convRMin_(cfg.exists("convRMin") ? cfg.getParameter<double>("convRMin") : 0.5),
    convRMax_(cfg.exists("convRMax") ? cfg.getParameter<double>("convRMax") : 5.0),
    applyMassConstraint_(cfg.exists("applyMassConstraint") ? cfg.getParameter<bool>("applyMassConstraint") : false),
    eleSelection_(cfg.getParameter<std::string>("eleSelection")),
    post_vtx_selection_(cfg.getParameter<std::string>("postVtxSelection")),
    bFieldToken_{esConsumes<MagneticField, IdealMagneticFieldRecord>()},
    dileptons_{consumes<pat::CompositeCandidateCollection>( cfg.getParameter<edm::InputTag>("dileptons") )},
    leptons_ttracks_{consumes<TransientTrackCollection>( cfg.getParameter<edm::InputTag>("leptonTransientTracks") )},
    electrons_(consumes<pat::CompositeCandidateCollection>(cfg.getParameter<edm::InputTag>("electrons"))),
    ele_ttracks_{consumes<TransientTrackCollection>( cfg.getParameter<edm::InputTag>("electronTransientTracks") )},
    beamspot_{consumes<reco::BeamSpot>( cfg.getParameter<edm::InputTag>("beamSpot") )}
  {
    produces<pat::CompositeCandidateCollection>();
  }

  ~BToMuMuGammaConvBuilder() override {}

  void produce(edm::StreamID, edm::Event&, const edm::EventSetup&) const override;

  static void fillDescriptions(edm::ConfigurationDescriptions &descriptions) {}

private:
  double bMassMin_, bMassMax_;
  double convRMin_, convRMax_;
  bool applyMassConstraint_;

  const StringCutObjectSelector<pat::CompositeCandidate> eleSelection_;
  const StringCutObjectSelector<pat::CompositeCandidate> post_vtx_selection_;

  // inputs
  const edm::ESGetToken<MagneticField, IdealMagneticFieldRecord> bFieldToken_;
  const edm::EDGetTokenT<pat::CompositeCandidateCollection> dileptons_;
  const edm::EDGetTokenT<TransientTrackCollection> leptons_ttracks_;
  const edm::EDGetTokenT<pat::CompositeCandidateCollection> electrons_;
  const edm::EDGetTokenT<TransientTrackCollection> ele_ttracks_;
  const edm::EDGetTokenT<reco::BeamSpot> beamspot_;
};

void BToMuMuGammaConvBuilder::produce(edm::StreamID, edm::Event &evt, edm::EventSetup const &iSetup) const {


//std::cout << "Start loop"<<std::endl;


  edm::Handle<reco::BeamSpot> beamspot;
  evt.getByToken(beamspot_, beamspot);

  edm::ESHandle<MagneticField> fieldHandle;
  const auto& bField = iSetup.getData(bFieldToken_);
  AnalyticalImpactPointExtrapolator extrapolator(&bField);


  // inputs
  edm::Handle<pat::CompositeCandidateCollection> dileptons;
  evt.getByToken(dileptons_, dileptons);


if (!dileptons.isValid()) {
std::cout << "No dileptons found: '";
  return; // or throw cms::Exception to fail fast with a clear message
}

  edm::Handle<TransientTrackCollection> leptons_ttracks;
  evt.getByToken(leptons_ttracks_, leptons_ttracks);

  edm::Handle<pat::CompositeCandidateCollection> electrons;
  evt.getByToken(electrons_, electrons);

if (!electrons.isValid()) {
std::cout<< "No electrons found: '" ;
  return; // or throw cms::Exception to fail fast with a clear message
}

  edm::Handle<TransientTrackCollection> ele_ttracks;
  evt.getByToken(ele_ttracks_, ele_ttracks);

  std::unique_ptr<pat::CompositeCandidateCollection> ret_val(new pat::CompositeCandidateCollection());


    // Loop over electron pairs (possible conversions)
    for (size_t e1_idx = 0; e1_idx < electrons->size(); ++e1_idx) {

      const auto& e1 = (*electrons)[e1_idx];
      if (!eleSelection_(e1)) continue;

      for (size_t e2_idx = e1_idx + 1; e2_idx < electrons->size(); ++e2_idx) {
        const auto& e2 = (*electrons)[e2_idx];
        if (!eleSelection_(e2)) continue;
        if ((e1.charge() + e2.charge()) != 0) continue;

    edm::Ptr<pat::CompositeCandidate> e1_ptr(electrons, e1_idx);
    if (!eleSelection_(*e1_ptr)) continue;
      edm::Ptr<pat::CompositeCandidate> e2_ptr(electrons, e2_idx);
      if (!eleSelection_(*e2_ptr)) continue;
      if ((e1_ptr->charge() + e2_ptr->charge()) != 0) continue;
      const auto& t1 = ele_ttracks->at(e1_idx);
      const auto& t2 = ele_ttracks->at(e2_idx);

        math::PtEtaPhiMLorentzVector e1_p4(e1_ptr->pt(), e1_ptr->eta(), e1_ptr->phi(), ELECTRON_MASS);
        math::PtEtaPhiMLorentzVector e2_p4(e2_ptr->pt(), e2_ptr->eta(), e2_ptr->phi(), ELECTRON_MASS);


        // DCA / POCA
        const auto& posImpact = t1.impactPointTSCP();
        const auto& negImpact = t2.impactPointTSCP();
        if (!posImpact.isValid() || !negImpact.isValid()) continue;
        const FreeTrajectoryState& posState = posImpact.theState();
        const FreeTrajectoryState& negState = negImpact.theState();
        ClosestApproachInRPhi cApp;
        cApp.calculate(posState, negState);
        if (!cApp.status()) continue;
        float dca = std::abs(cApp.distance());
        GlobalPoint cxPt = cApp.crossingPoint();
        const double cxPtR = std::sqrt(cxPt.x()*cxPt.x() + cxPt.y()*cxPt.y());
        // crossing point should be inside detector
        if (cxPtR > 120. || std::abs(cxPt.z()) > 300.) continue;

        // Vertex fit: Kalman vertex fitter for the two electrons
        std::vector<reco::TransientTrack> transTracks{t1, t2};
        KalmanVertexFitter theKalmanFitter(true);
        TransientVertex theRecoVertex = theKalmanFitter.vertex(transTracks);
        if (!theRecoVertex.isValid()) continue;
        reco::Vertex theVtx_KLM = reco::Vertex(theRecoVertex);
        GlobalPoint vtxPos(theVtx_KLM.x(), theVtx_KLM.y(), theVtx_KLM.z());
        double vtxR = std::sqrt(vtxPos.x()*vtxPos.x() + vtxPos.y()*vtxPos.y());

        // basic conv radius window selection
        if (vtxR < convRMin_ || vtxR > convRMax_) continue;

        // Optionally perform mass-constrained fit (mass = 0) using KinVtxFitter (preferred pattern)
        bool massConstraintSuccess = false;
        double constrainedMass = -1.0;
        math::PtEtaPhiMLorentzVector conv_p4;
        // placeholders for constraint-derived outputs
        double constraint_sv_prob = -99.;
        double constraint_pt = -99.;
        double constraint_eta = -99.;
        double constraint_phi = -99.;
        double constraint_mass = -99.;
        double constraint_massErr = -99.;
        double constraint_mll = -99.;
        if (applyMassConstraint_) {
          // Use KinVtxFitter to apply an m=0 constraint to the first two particles (the electrons)
          KinVtxFitter constraint_fitter(
            { t1, t2 },
            { ELECTRON_MASS, ELECTRON_MASS },
            { (float)ELECTRON_SIGMA, (float)ELECTRON_SIGMA },
            0.0 // dilepton mass constraint (photon mass = 0)
          );
          if (constraint_fitter.success()) {
            constrainedMass = constraint_fitter.fitted_candidate().mass();
            conv_p4 = constraint_fitter.fitted_p4();
            // override the vertex info with the kinematic fit result
            GlobalPoint kVtx = constraint_fitter.fitted_vtx();
            vtxPos = kVtx;
            vtxR = std::sqrt(vtxPos.x()*vtxPos.x() + vtxPos.y()*vtxPos.y());
            // save constraint-derived summary vars into placeholders
            constraint_sv_prob = constraint_fitter.prob();
            auto cfit_p4 = constraint_fitter.fitted_p4();
            constraint_pt = cfit_p4.pt();
            constraint_eta = cfit_p4.eta();
            constraint_phi = cfit_p4.phi();
            constraint_mass = constraint_fitter.fitted_candidate().mass();
            constraint_massErr = sqrt(constraint_fitter.fitted_candidate().kinematicParametersError().matrix()(6, 6));
            constraint_mll = (constraint_fitter.daughter_p4(0) + constraint_fitter.daughter_p4(1)).mass();
            massConstraintSuccess = true;
          }
        }

        // If mass constraint not applied or failed, use simple sum of electron 4-vectors
        if (!massConstraintSuccess) {
          math::PtEtaPhiMLorentzVector e1_p4(e1.pt(), e1.eta(), e1.phi(), ELECTRON_MASS);
          math::PtEtaPhiMLorentzVector e2_p4(e2.pt(), e2.eta(), e2.phi(), ELECTRON_MASS);
          conv_p4 = e1_p4 + e2_p4;
        }

        // compute pointing angle wrt beamspot (or PV if available)
        math::XYZVector conv_mom(conv_p4.px(), conv_p4.py(), conv_p4.pz());
        math::XYZVector disp(vtxPos.x() - beamspot->x0(), vtxPos.y() - beamspot->y0(), vtxPos.z() - beamspot->z0());
        double cos_pointing = (conv_mom.Dot(disp) / (conv_mom.R() * disp.R()));

//std::cout << "Get gamma->electrons"<<std::endl;;

  for (size_t ll_idx = 0; ll_idx < dileptons->size(); ++ll_idx) {
    edm::Ptr<pat::CompositeCandidate> ll_ptr(dileptons, ll_idx);

        edm::Ptr<reco::Candidate> l1_ptr = ll_ptr->userCand("l1");
        edm::Ptr<reco::Candidate> l2_ptr = ll_ptr->userCand("l2");

        // Build B candidate: use dilepton p4 + conv_p4
        math::PtEtaPhiMLorentzVector l1_p4(l1_ptr->pt(), l1_ptr->eta(), l1_ptr->phi(), MUON_MASS);
        math::PtEtaPhiMLorentzVector l2_p4(l2_ptr->pt(), l2_ptr->eta(), l2_ptr->phi(), MUON_MASS);
        auto dilep_p4 = l1_p4 + l2_p4;
        // dielectron (conversion) 4-vector is `conv_p4` (may be mass-constrained)
        auto b_p4 = dilep_p4 + conv_p4;
        double m_b = b_p4.mass();
        if (m_b < bMassMin_ || m_b > bMassMax_) continue;


//std::cout << "Get All"<<std::endl;;

        pat::CompositeCandidate cand;
        cand.addUserCand("e1", e1_ptr);
        cand.addUserCand("e2", e2_ptr);
        cand.setCharge(l1_ptr->charge() + l2_ptr->charge() + e1_ptr->charge() + e2_ptr->charge());
        cand.setP4(b_p4);
        // save daughters
        /*
        cand.addUserCand("l1", l1_ptr);
        cand.addUserCand("l2", l2_ptr);
        cand.addUserCand("e1", edm::Ptr<reco::Candidate>(electrons, e1_idx));
        cand.addUserCand("e2", edm::Ptr<reco::Candidate>(electrons, e2_idx));
        */

        // indices
        cand.addUserInt("ll_idx", ll_idx);
        cand.addUserInt("e1_idx", e1_idx);
        cand.addUserInt("e2_idx", e2_idx);

        // conv info
        cand.addUserFloat("conv_vtx_x", vtxPos.x());
        cand.addUserFloat("conv_vtx_y", vtxPos.y());
        cand.addUserFloat("conv_vtx_z", vtxPos.z());
        cand.addUserFloat("conv_vtx_r", vtxR);
        cand.addUserFloat("conv_chi2", theVtx_KLM.chi2());
        cand.addUserFloat("conv_ndof", theVtx_KLM.ndof());
        cand.addUserFloat("conv_prob", ChiSquaredProbability(theVtx_KLM.chi2(), theVtx_KLM.ndof()));
        cand.addUserFloat("conv_dca", dca);
        cand.addUserFloat("conv_poca_x", cxPt.x());
        cand.addUserFloat("conv_poca_y", cxPt.y());
        cand.addUserFloat("conv_poca_z", cxPt.z());
        cand.addUserFloat("conv_poca_r", cxPtR);
        cand.addUserFloat("conv_pointing_cos", (float)cos_pointing);
        cand.addUserFloat("conv_mass", (float)conv_p4.mass());
        cand.addUserFloat("conv_mass_constrained", (float)constrainedMass);

        // dielectron 4-vector components
        cand.addUserFloat("conv_pt", conv_p4.pt());
        cand.addUserFloat("conv_eta", conv_p4.eta());
        cand.addUserFloat("conv_phi", conv_p4.phi());

        // dimuon (dilepton) 4-vector components
        cand.addUserFloat("dilep_pt", dilep_p4.pt());
        cand.addUserFloat("dilep_eta", dilep_p4.eta());
        cand.addUserFloat("dilep_phi", dilep_p4.phi());
        cand.addUserFloat("dilep_mass", dilep_p4.mass());

        // constraint-derived summary variables (if applied)
        cand.addUserFloat("conv_constraint_sv_prob", (float)constraint_sv_prob);
        cand.addUserFloat("conv_constraint_pt", (float)constraint_pt);
        cand.addUserFloat("conv_constraint_eta", (float)constraint_eta);
        cand.addUserFloat("conv_constraint_phi", (float)constraint_phi);
        cand.addUserFloat("conv_constraint_mass", (float)constraint_mass);
        cand.addUserFloat("conv_constraint_massErr", (float)constraint_massErr);
        cand.addUserFloat("conv_constraint_mll", (float)constraint_mll);

        // some basic kinematics
        cand.addUserFloat("fitted_pt", b_p4.pt());
        cand.addUserFloat("fitted_eta", b_p4.eta());
        cand.addUserFloat("fitted_phi", b_p4.phi());
        cand.addUserFloat("fitted_mass", b_p4.mass());

        if (!post_vtx_selection_(cand)) continue;

        ret_val->push_back(cand);
      }
    }
  }

  evt.put(std::move(ret_val));
}

#include "FWCore/Framework/interface/MakerMacros.h"
DEFINE_FWK_MODULE(BToMuMuGammaConvBuilder);
